POSSIBLE_JOB_LABELS = [
						'Accountants',
						'Ag labour',
						'Air/ship officers',
						'Artists',
						'Assemblers',
						'Barbers',
						'Boilermen',
						'Book-keepers',
						'Carpenters',
						'Chemical',
						'Cinema op',
						'Clerical nec',
						'Clerical supe',
						'Computing op',
						'Construction',
						'Cooks/waiters',
						'Cultivators',
						'Drivers',
						'Economists',
						'Elected officials',
						'Electrical',
						'Eng. tech',
						'Engineers',
						'FIRE sales',
						'Farm manager',
						'Fishermen',
						'Food',
						'Forestry',
						'Govt officials',
						'Homebound',
						'Hotel/restaurant',
						'House keepers',
						'Hunters',
						'Jewellery',
						'Journalists',
						'Labour nec',
						'Launderers',
						'Lawyers',
						'Life science tech',
						'Life scientists',
						'Loaders',
						'Machine tool op',
						'Maids',
						'Mail distributors',
						'Managerial nec',
						'Manuf agents',
						'Metal workers',
						'Mgr Whsl/retail',
						'Mgr finance',
						'Mgr manf',
						'Mgr service',
						'Mgr transp/commun',
						'Miners',
						'Money lenders',
						'Nursing',
						'Other farm',
						'Other farmers',
						'Other scientific',
						'Painters',
						'Paper',
						'Performers',
						'Physical sci tech',
						'Physicians',
						'Plantation lab',
						'Plumbers/welders',
						'Police',
						'Potters',
						'Printing',
						'Production nec',
						'Professional nec',
						'Rubber/plastic',
						'Sales, nec',
						'Sales, shop',
						'Service nec',
						'Shoe makers',
						'Shopkeepers',
						'Social scientists',
						'Statisticians',
						'Stone cutters',
						'Sweepers',
						'Tailors',
						'Tanners',
						'Teachers',
						'Technical sales',
						'Telephone op',
						'Textile',
						'Tobacco',
						'Transp conductors',
						'Transp/commun supe',
						'Typists',
						'Unidentifiable occ',
						'Village officials',
						'Wood/paper'
]
