POSSIBLE_JOB_LABELS = [
						'Accountants',
						'Ag labour',
						'Air/ship officers',
						'Artists',
						'Assemblers',
						'Barbers',
						'Boilermen',
						'Book-keepers',
						'Carpenters',
						'Chemical',
						'Cinema op',
						'Clerical nec',
						'Clerical supe',
						'Computing op',
						'Construction',
						'Cooks/waiters',
						'Cultivators',
						'Drivers',
						'Economists',
						'Elected officials',
						'Electrical',
						'Eng. tech',
						'Engineers',
						'FIRE sales',
						'Farm manager',
						'Fishermen',
						'Food',
						'Forestry',
						'Govt officials',
						'Homebound',
						'Hotel/restaurant',
						'House keepers',
						'Hunters',
						'Jewellery',
						'Journalists',
						'Labour nec',
						'Launderers',
						'Lawyers',
						'Life science tech',
						'Life scientists',
						'Loaders',
						'Machine tool op',
						'Maids',
						'Mail distributors',
						'Managerial nec',
						'Manuf agents',
						'Metal workers',
						'Mgr Whsl/retail',
						'Mgr finance',
						'Mgr manf',
						'Mgr service',
						'Mgr transp/commun',
						'Miners',
						'Money lenders',
						'Nursing',
						'Other farm',
						'Other farmers',
						'Other scientific',
						'Painters',
						'Paper',
						'Performers',
						'Physical sci tech',
						'Physicians',
						'Plantation lab',
						'Plumbers/welders',
						'Police',
						'Potters',
						'Printing',
						'Production nec',
						'Professional nec',
						'Rubber/plastic',
						'Sales, nec',
						'Sales, shop',
						'Service nec',
						'Shoe makers',
						'Shopkeepers',
						'Social scientists',
						'Statisticians',
						'Stone cutters',
						'Sweepers',
						'Tailors',
						'Tanners',
						'Teachers',
						'Technical sales',
						'Telephone op',
						'Textile',
						'Tobacco',
						'Transp conductors',
						'Transp/commun supe',
						'Typists',
						'Unidentifiable occ',
						'Village officials',
						'Wood/paper'
]

# POSSIBLE_JOB_LABELS = ['Worker']

IHDS_II_STATE_ID_TO_NAME = {
	1: 'Jammu & Kashmir',
	2: 'Himachal Pradesh',
	3: 'Punjab',
	4: 'Chandigarh',
	5: 'Uttarakhand',
	6: 'Haryana',
	7: 'Delhi',
	8: 'Rajasthan',
	9: 'Uttar Pradesh',
	10: 'Bihar',
	11: 'Sikkim',
	12: 'Arunachal Pradesh',
	13: 'Nagaland',
	14: 'Manipur',
	15: 'Mizoram',
	16: 'Tripura',
	17: 'Meghalaya',
	18: 'Assam',
	19: 'West Bengal',
	20: 'Jharkhand',
	21: 'Orissa',
	22: 'Chhattisgarh',
	23: 'Madhya Pradesh',
	24: 'Gujarat',
	25: 'Daman & Diu',
	26: 'Dadra+Nagar Haveli',
	27: 'Maharashtra',
	28: 'Andhra Pradesh',
	29: 'Karnataka',
	30: 'Goa',
	31: 'Lakshadweep',
	32: 'Kerala',
	33: 'Tamil Nadu',
	34: 'Pondicherry',
	35: 'Anadman/Nicobar'
}

IHDS_II_STATE_NAME_TO_ID = {
	'Jammu & Kashmir': 1,
	'Himachal Pradesh': 2,
	'Punjab': 3,
	'Chandigarh': 4,
	'Uttarakhand': 5,
	'Haryana': 6,
	'Delhi': 7,
	'Rajasthan': 8,
	'Uttar Pradesh': 9,
	'Bihar': 10,
	'Sikkim': 11,
	'Arunachal Pradesh': 12,
	'Nagaland': 13,
	'Manipur': 14,
	'Mizoram': 15,
	'Tripura': 16,
	'Meghalaya': 17,
	'Assam': 18,
	'West Bengal': 19,
	'Jharkhand': 20,
	'Orissa': 21,
	'Chhattisgarh': 22,
	'Madhya Pradesh': 23,
	'Gujarat': 24,
	'Daman & Diu': 25,
	'Dadra+Nagar Haveli': 26,
	'Maharashtra': 27,
	'Andhra Pradesh': 28,
	'Karnataka': 29,
	'Goa': 30,
	'Lakshadweep': 31,
	'Kerala': 32,
	'Tamil Nadu': 33,
	'Pondicherry': 34,
	'Anadman/Nicobar': 35
}

